### ISSUE TITLE
exec_rollback_db_transaction raises error when SQL-Query creates error

### ISSUE THREAD

**Issue by RobWu** [rails-sqlserver/tiny_tds#267]
I try to create a new barcode.

```ruby
Barcode.create!(member_shiporder_line_id: 904577)
```
This executes:
```ruby
@connection.execute(BEGIN TRANSACTION).do
  SQL (6.5ms)  BEGIN TRANSACTION
  SQL (9.1ms)  EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577  [["membershiporderlineid", 904577]]

@connection.execute(IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION).do
  SQL (8.0ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION

ActiveRecord::StatementInvalid: TinyTds::Error: The request failed to run because the batch is aborted, this can be caused by abort signal sent from client, or another request is running in the same session, which makes the session busy.: IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:302:in `do'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:302:in `raw_connection_do'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:254:in `block in do_execute'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activesupport-4.2.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:254:in `do_execute'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-sqlserver-adapter-4.2.10/lib/active_record/connection_adapters/sqlserver/database_statements.rb:69:in `exec_rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:266:in `rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `rollback_db_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:145:in `rollback'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:179:in `rollback_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:187:in `rescue in within_new_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:202:in `within_new_transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:220:in `transaction'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/transactions.rb:291:in `save!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/activerecord-4.2.6/lib/active_record/persistence.rb:51:in `create!'
	from (irb):7
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/row/.rvm/gems/ruby-2.3.0@biografklub/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:9:in `require'
	from bin/rails:9:in `<main>'2.3.0 :008 > exit
```

Looks like there is an exceptions for the ```create!``` call.. 
```
DEBUG INFO : # PUTS inside gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/transaction.rb:187:in `rescue in within_new_transaction'

 - #<ActiveRecord::StatementInvalid: TinyTds::Error: Cannot insert the value NULL into column 'barcode_postfix', table 'prod_2015_bio_membership_rhg_dev.dbo.Barcode'; column does not allow nulls. INSERT fails.: EXEC sp_executesql N'INSERT INTO [barcode] ([membershiporderlineid]) OUTPUT INSERTED.[id] VALUES (@0)', N'@0 int', @0 = 904577>
```

Because of this exception, ```exec_rollback_db_transaction``` will be executed, and created a new and different error (```The request failed to run because the batch is aborted...```), and hides the original error (```Cannot insert the value NULL into column```) at the same time..

**Comment by metaskills** [comment]
Thanks for the report. A few things.

* Could you open an issue with the same details on the [adapter issues](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/issues) where this belongs?
* When doing so, could you give me a few details on how to reproduce this? What do the Rails models look like. DB constraints.
* Please include details of the version of TinyTDS, FreeTDS, and what DB version you are using.

I will admit that I am super confused by this. I am almost certain there are test in ActiveRecord that test the failure of a NULL constraint and I have yet to see this. So details are important. Looking forward to it.
