### ISSUE TITLE
Fail to stablish connection with TinyTDS version 1.0.1

### ISSUE THREAD

**Issue by alvarocantador** [rails-sqlserver/tiny_tds#269]
I forced downgrade to version 0.7.0 and it worked.

`client = TinyTds::Client.new username: 'user', password: 'password', host: 'example.com'`

Stack Trace:

```
SystemStackError: stack level too deep
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/tiny_tds-1.0.1/lib/tiny_tds/client.rb:43:in `connect'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/tiny_tds-1.0.1/lib/tiny_tds/client.rb:43:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /home/alvaro/Workspace/bitbucket.org/pinho/bl-import/bin/rails:9:in `<top (required)>'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/commands/rails.rb:6:in `call'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/command_wrapper.rb:38:in `call'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:191:in `block in serve'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:161:in `fork'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:161:in `serve'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:131:in `block in run'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:125:in `loop'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application.rb:125:in `run'
	from /home/alvaro/.rvm/gems/ruby-2.2.1/gems/spring-1.7.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /home/alvaro/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/alvaro/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'2.2.1 :005 > exit

```

PS:  tsql command run with success with the same connection parameters

**Comment by metaskills** [comment]
What version of FreeTDS do you have installed to compile against? What platform?

**Comment by alvarocantador** [comment]
OS: Debian 8.4
```
alvaro@machine:~$ dpkg-query -l | grep freetds
ii  freetds-bin                           0.91-6+b1                            amd64        FreeTDS command-line utilities
ii  freetds-common                        0.91-6                               all          configuration files for FreeTDS SQL client libraries
ii  freetds-dev                           0.91-6+b1                            amd64        MS SQL and Sybase client library (static libs and headers)
```

**Comment by metaskills** [comment]
So I think you need 0.95 for the latest, we no longer test on 0.91.

**Comment by alvarocantador** [comment]
Oh Ok, 0.91 the last on the Debian repo
I  will close this issue. Thanks!
