### ISSUE TITLE
TinyTds::Error·Adaptive Server connection failed

### ISSUE THREAD

**Issue by sunsations** [rails-sqlserver/tiny_tds#277]
Upgraded from version 0.7.0 to version 1.0.2 and got the following error: `TinyTds::Error·Adaptive Server connection failed`.  I downgraded again and it work fine. Thus, I expect it's an issue with the new version.

Full backtrace:
`````
from /prod_path/shared/bundle/ruby/2.1.0/gems/tiny_tds-1.0.2/lib/tiny_tds/client.rb:43:in `connect'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/tiny_tds-1.0.2/lib/tiny_tds/client.rb:43:in `initialize'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/connection_adapters/sqlserver_adapter.rb:311:in `new'
from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/connection_adapters/sqlserver_adapter.rb:311:in `dblib_connect'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/connection_adapters/sqlserver_adapter.rb:302:in `connect'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/connection_adapters/sqlserver_adapter.rb:58:in `initialize'
from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/sqlserver_base.rb:17:in `new'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-sqlserver-adapter-4.2.11/lib/active_record/sqlserver_base.rb:17:in `sqlserver_connection'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
from /home/etrans/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
from /home/etrans/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
... 4 levels...
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/attributes.rb:93:in `columns'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/model_schema.rb:260:in `column_names'
from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:226:in `aggregate_column'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:252:in `execute_simple_calculation'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:221:in `perform_calculation'
from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:127:in `calculate'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/relation/calculations.rb:42:in `count'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/activerecord-4.2.6/lib/active_record/querying.rb:13:in `count'
from (irb):1
from /prod_path/shared/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/commands/console.rb:110:in `start'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/commands/console.rb:9:in `start'
        from /prod_path/shared/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:68:in `console'
from /prod_path/shared/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /etransform/etransform-3/shared/bundle/ruby/2.1.0/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
````

The ruby version is 2.1.5 on Red Hat Linux.

**Comment by metaskills** [comment]
What version of FreeTDS are you using? It should be 0.95 or higher for the latest gem.

**Comment by sunsations** [comment]
Thanks for the update. We are using freetds version 0.9.1

**Comment by metaskills** [comment]
That's the issue. I recommend using the latest 0.95, 0.99 or even the 1.0 release candidate. You will need to uninstall the gem and re-install once you get the right version of FreeTDS installed. Hope that helps.

**Comment by sunsations** [comment]
Update to freetds version 0.95 solved to problem. Thank your for your held and work!
