### ISSUE TITLE
Installation of 1.0.3 uses FTP

### ISSUE THREAD

**Issue by camhine** [rails-sqlserver/tiny_tds#283]
Looks like installation of version 1.0.3 reaches out to ftp.freetds.org on port 21.

1.0.2 does not.

Is this a desired behaviour? FTP is not going to get through the corporate firewall.

Here it is:

```
Installing tiny_tds 1.0.3 (was 1.0.2) with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /tmp/bundler20160520-19084-1ck9sahtiny_tds-1.0.3/gems/tiny_tds-1.0.3/ext/tiny_tds
/usr/local/bin/ruby -r ./siteconf20160520-19084-kd750y.rb extconf.rb
extconf.rb:14: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
checking for sybfront.h... yes
checking for sybdb.h... yes
checking for tdsdbopen() in -lsybdb... yes
checking for dbanydatecrack() in -lsybdb... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --help
        --enable-lookup
        --disable-lookup
        --with-freetds-dir
        --without-freetds-dir
        --with-freetds-include
        --without-freetds-include=${freetds-dir}/include
        --with-freetds-lib
        --without-freetds-lib=${freetds-dir}/lib
        --with-sybdblib
        --without-sybdblib
        --with-sybdblib
        --without-sybdblib
        --enable-system-freetds
        --disable-system-freetds
        --enable-system-iconv
        --disable-system-iconv
        --enable-system-openssl
        --disable-system-openssl
        --enable-gnutls
        --disable-gnutls
        --enable-openssl
        --disable-openssl
/usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in `initialize': Connection timed out - connect(2) for "ftp.freetds.org" port 21 (Errno::ETIMEDOUT)
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in `open'
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:243:in `block in open_socket'
        from /usr/local/lib/ruby/2.3.0/timeout.rb:74:in `timeout'
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:238:in `open_socket'
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:263:in `block in connect'
        from /usr/local/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
        from /usr/local/lib/ruby/2.3.0/net/ftp.rb:262:in `connect'
        from /usr/local/lib/ruby/2.3.0/open-uri.rb:775:in `buffer_open'
        from /usr/local/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from /usr/local/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from /usr/local/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:479:in `block in download_file_ftp'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:491:in `with_tempfile'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:460:in `download_file_ftp'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:399:in `download_file'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:50:in `block in download'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:49:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:49:in `download'
        from /usr/local/lib/ruby/gems/2.3.0/gems/mini_portile2-2.1.0/lib/mini_portile2/mini_portile.rb:146:in `cook'
        from extconf.rb:128:in `block in cook_and_activate'
        from extconf.rb:120:in `block in chdir_for_build'
        from extconf.rb:119:in `chdir'
        from extconf.rb:119:in `chdir_for_build'
        from extconf.rb:127:in `cook_and_activate'
        from extconf.rb:321:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /tmp/bundler20160520-19084-1ck9sahtiny_tds-1.0.3/extensions/x86_64-linux/2.3.0-static/tiny_tds-1.0.3/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /tmp/bundler20160520-19084-1ck9sahtiny_tds-1.0.3/gems/tiny_tds-1.0.3 for inspection.
Results logged to /tmp/bundler20160520-19084-1ck9sahtiny_tds-1.0.3/extensions/x86_64-linux/2.3.0-static/tiny_tds-1.0.3/gem_make.out
```

**Comment by metaskills** [comment]
Please install FreeTDS v0.95 or higher first.
