### ISSUE TITLE
Cannot require tiny_tds after yaml

### ISSUE THREAD

**Issue by bk5115545** [rails-sqlserver/tiny_tds#287]
I'm writing an application that uses both yaml and tiny_tds.

The below code executes correctly.
```ruby
require 'tiny_tds'
require 'yaml'

database_config = YAML.load_file('../private/database_creds.yml')
database_options = {
  host: database_config["host"],
  database: database_config["database"],
  username: database_config["username"],
  password: database_config["password"]
}

client = TinyTds::Client.new database_options
```

But when I change the require order to 
```ruby 
require 'yaml'
require 'tiny_tds'
``` 

I get the following stack trace
```
C:/Ruby200/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require': cannot load such file -- tiny_tds/tiny_tds (LoadError)
        from C:/Ruby200/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
        from C:/Ruby200/lib/ruby/gems/2.3.0/gems/tiny_tds-1.0.4-x64-mingw32/lib/tiny_tds.rb:22:in `rescue in <top (required)>'
        from C:/Ruby200/lib/ruby/gems/2.3.0/gems/tiny_tds-1.0.4-x64-mingw32/lib/tiny_tds.rb:25:in `<top (required)>'
        from C:/Ruby200/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby200/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby200/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
        from manager_data_build.rb:12:in `<main>'
```

Is this is bug in tiny_tds?

**Comment by metaskills** [comment]
WOW, that is odd. We test this gem with Rail in the SQL Server repo on Windows and things work fine. I suspect that yaml is required there before TinyTDS too and works fine. 

Can you debug what your `ENV['PATH']` looks like before after each require to see what may be happening. This is the code that is now suspect https://github.com/rails-sqlserver/tiny_tds/blob/master/lib/tiny_tds.rb#L12-L25

**Comment by bk5115545** [comment]
This might also be odd but I'm not sure. `ENV['PATH']` is the same throughout the entire file.  It doesn't change when I require yaml or TinyTDS.

Also something majorly wrong is going on.  Out of 25 executions, 2 times it executed correctly (it was the first one which made me try it a lot and like number 19).  The paths were not different on these executions.

Full test script is below.
```
require 'yaml'
begin
  require 'tiny_tds'
rescue LoadError => ex
  joined = ex.backtrace.join("\n")
  print "ERROR: #{joined}\n\n"
  exit
  # if we don't exit here then we get NoSuchMethod errors for Client.new
  # but not for referencing TinyTds (which is odd)
end

# Client.new doesn't like the hash-like object returned from YAML.load_file
# so make a literal hash to pass
options = YAML.load_file('../private/database_creds.yml')
database_options = {
  host: database_config["host"],
  database: database_config["database"],
  username: database_config["username"],
  password: database_config["password"]
}

client = TinyTds::Client.new database_options
print "Client.active? = #{client.active?}\n"

result = client.execute("SELECT * FROM Privileges")
result.each(:symbolize_keys => true) { |entry|
  print entry.inspect
  print "\n"
}
```

**Comment by metaskills** [comment]
Closing this since #290 seems to represent the conversation better.
