### ISSUE TITLE
rake gem:windows returns NameError: uninitialized constant Rake::ExtensionTask

### ISSUE THREAD

**Issue by bradder555** [rails-sqlserver/tiny_tds#328]
Hi There

I am using Windows 10 Home, can you get 32 bit windows 10?

Started off with railsinstaller ruby 2.2.6 

Installed rails 4.2.7.1, and created a new rails project as per rails-sqlserver.

Installed FreeTDS 1.0 which is on the path, also have environment variables "FREETDS" to "C:\conf\freetds.conf" contents:
```
[mssql]
host = localhost
port = 1433
tds version = 7.3
```

C:\freetds-1.00\bin is on my path

Running Sql Server 2016 Development

So I install tiny_tds, run cmd from "C:\RailsInstaller\Ruby2.2.0\lib\ruby\gems\2.2.0\gems\tiny_tds-1.1.0-x86-mingw32" then run "rake gem:windows --trace" (trace for the purposes of this issue)

I get the following:
C:\RailsInstaller\Ruby2.2.0\lib\ruby\gems\2.2.0\gems\tiny_tds-1.1.0-x86-mingw32>rake gem:windows --trace
```
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
rake aborted!
NameError: uninitialized constant Rake::ExtensionTask
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/tiny_tds-1.1.0-x86-mingw32/Rakefile:57:in `<top (required)>'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/rake_module.rb:28:in `load_rakefile'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:687:in `raw_load_rakefile'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:96:in `block in load_rakefile'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:95:in `load_rakefile'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:79:in `block in run'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
C:/RailsInstaller/Ruby2.2.0/bin/rake:33:in `<main>'

```
I'm sure this is operator error, but i'm going around in circles.  Thanks!

PS, if i run "rails _4.2.7.1_ s" from the MYAPP dir, I get "cannot load such file -- tiny_tds"
Started GET "/" for ::1 at 2016-12-27 23:09:02 +0800

```
LoadError (cannot load such file -- tiny_tds):
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:274:in `require'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:274:in `block in require'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:240:in `load_dependency'
  activesupport (4.2.7.1) lib/active_support/dependencies.rb:274:in `require'
  activerecord-sqlserver-adapter (4.2.15) lib/active_record/sqlserver_base.rb:9:in `sqlserver_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.7.1) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.7.1) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.7.1) lib/active_record/migration.rb:383:in `connection'
  activerecord (4.2.7.1) lib/active_record/migration.rb:370:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `catch'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.5) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.5) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
  rack (1.6.5) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.7.1) lib/rails/application.rb:165:in `call'
  rack (1.6.5) lib/rack/lock.rb:17:in `call'
  rack (1.6.5) lib/rack/content_length.rb:15:in `call'
  rack (1.6.5) lib/rack/handler/webrick.rb:88:in `service'
  C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
  C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
  C:/RailsInstaller/Ruby2.2.0/lib/ruby/2.2.0/webrick/server.rb:294:in `block in start_thread'

```

**Comment by metaskills** [comment]
Quick question, why are you running `rake gem:windows` vs installing them gem which has a statically compiled FreeTDS, OpenSSL, etc for you?

**Comment by bradder555** [comment]
I set everything up as per rails-sqlserver/activerecord-sqlserver-adapter and this was the rabbit hole i eventually followed.

I can run a test rails project, if i manually set the tiny_tds version to 64 bit, unfortunately if i bundle update the project, the 32 bit version is installed and added to my lock file. It's very frustrating, i can't seem to find a means of forcing the 64 bit version in my bundle file.
