### ISSUE TITLE
Problem running tests: cannot load such file -- tiny_tds/tiny_tds (LoadError)

### ISSUE THREAD

**Issue by aharpervc** [rails-sqlserver/tiny_tds#381]
I'm on Ubuntu 16.04.1 LTS (WSL) with Ruby 2.4.1, and tiny_tds builds and installs and runs fine in my app. 

However, `rake test` fails with `cannot load such file -- tiny_tds/tiny_tds (LoadError)`. I'm got the latest commits from master.

The sequence of commands to prepare is:

```sh
$ cd to/tiny_tds/dir
$ rake clobber
$ rake gem
$ gem install pkg/tiny_tds-2.1.0.pre2.gem
```

Then:

```sh
$ rake test --trace
/mnt/c/Users/aharper/workspace/tiny_tds/tiny_tds.gemspec:14: warning: Insecure world writable dir /home/aharper/.rbenv/plugins/ruby-build/bin in PATH, mode 040777
tasks/ports.rake:9: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
** Invoke test (first_time)
** Execute test
/home/aharper/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:test" -I"/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/client_test.rb" "test/gem_test.rb" "test/result_test.rb" "test/schema_test.rb" "test/thread_test.rb"
/mnt/c/Users/aharper/workspace/tiny_tds/lib/tiny_tds.rb:60:in `require': cannot load such file -- tiny_tds/tiny_tds (LoadError)
        from /mnt/c/Users/aharper/workspace/tiny_tds/lib/tiny_tds.rb:60:in `<top (required)>'
        from /mnt/c/Users/aharper/workspace/tiny_tds/test/test_helper.rb:3:in `require'
        from /mnt/c/Users/aharper/workspace/tiny_tds/test/test_helper.rb:3:in `<top (required)>'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /mnt/c/Users/aharper/workspace/tiny_tds/test/client_test.rb:2:in `<top (required)>'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:15:in `block in <main>'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `select'
        from /home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb:4:in `<main>'
rake aborted!
Command failed with status (1): [ruby -w -I"lib:test" -I"/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib" "/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/rake_test_loader.rb" "test/client_test.rb" "test/gem_test.rb" "test/result_test.rb" "test/schema_test.rb" "test/thread_test.rb" ]
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:128:in `block (3 levels) in define'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils.rb:56:in `sh'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils.rb:104:in `ruby'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:115:in `block (2 levels) in define'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/file_utils_ext.rb:58:in `verbose'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/testtask.rb:109:in `block in define'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:80:in `block in run'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
/home/aharper/.rbenv/versions/2.4.1/bin/rake:22:in `load'
/home/aharper/.rbenv/versions/2.4.1/bin/rake:22:in `<main>'
Tasks: TOP => test
```

I'm kind of stumped on why the require doesn't work, because again, in a scratch ruby program it loads and runs fine. And I can require in `irb` fine:

```sh
$ irb
irb(main):001:0> require 'tiny_tds'
=> true
irb(main):002:0> TinyTds::VERSION
=> "2.1.0.pre2"
```

Hopefully this is something dumb/obvious on my end...

**Comment by metaskills** [comment]
What does `$ gem env` show?

**Comment by aharpervc** [comment]
```sh
$ gem env
/home/aharper/.rbenv/versions/2.4.1/lib/ruby/2.4.0/rubygems/commands/environment_command.rb:154: warning: Insecure world writable dir /home/aharper/.rbenv/plugins/ruby-build/bin in PATH, mode 040777
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /home/aharper/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/aharper/.rbenv/versions/2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/aharper/.rbenv/versions/2.4.1/bin
  - SPEC CACHE DIRECTORY: /home/aharper/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/aharper/.rbenv/versions/2.4.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/aharper/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
     - /home/aharper/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "install" => "--no-rdoc --no-ri"
     - "update" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/aharper/.rbenv/versions/2.4.1/bin
     - /home/aharper/.rbenv/libexec
     - /home/aharper/.rbenv/plugins/ruby-build/bin
     - /home/aharper/.rbenv/shims
     - /home/aharper/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
```

**Comment by metaskills** [comment]
Also... I would be interested in what this does:

```shell
$ cd to/tiny_tds/dir
$ rake clobber
$ gem build tiny_tds.gemspec
$ gem install tiny_tds-2.1.0.pre3.gem
```

My guess is the rake task is building a gem with static libs and you just need a bare bones gem. When I publish the basic gem, I always use `gem build`.

**Comment by aharpervc** [comment]
Same error & stack trace. I did `gem uninstall` the previous one first, too.

**Comment by metaskills** [comment]
When you run `rake test --trace` it is supposed to fail because there literally is no built binary in the local folder. Running test is about testing the local dir, not an installed gem.

**Comment by coderjoe** [comment]
What's the end goal here? Functioning development environment? Or installed gem?

**Comment by aharpervc** [comment]
> Running test is about testing the local dir, not an installed gem.

Oh, duh, so of course the gem build process is irrelevant. But still, that doesn't explain why `rake test` doesn't work in a clean checkout.

> What's the end goal here?

Being able to run tests for development instead of eyeballing & waiting on CI

**Comment by aharpervc** [comment]
I needed to run `rake compile` first... I thought that building them gem included the compile step automatically, but it doesn't work like that.

**Comment by metaskills** [comment]
> Being able to run tests for development instead of eyeballing & waiting on CI

Oh... this is why we hook up the default task to build (clean, compile) and test. So running `bundle exec rake` does it all. See here: https://github.com/rails-sqlserver/tiny_tds/blob/master/Rakefile#L52

**Comment by coderjoe** [comment]
@metaskills nailed it. 

When testing locally you need to make sure you use the full build chain. This is either done by installing the prerequisite libraries and building via `rake build` or running build/test with `rake` or `rake build test`.

Alternatively if you're in an environment where installing the prerequisite requirements (FreeTDS etc..) for testing the gem becomes difficult or impossible you can use the miniportile build system to compile local libraries for testing.

Setting this up is done by prefacing any build steps with the "ports" step.

`rake ports build test` would build all the miniportile ports in a local library and set up the runtime environment to load those dynamic libraries in preference over system libraries.

This can be useful if, like me, you don't like installing system wide libraries that aren't distribution supported, or you want to try newer versions of libraries than are packaged for your system.
