### ISSUE TITLE
Sporadic errors when trying to connect to Azure sql db

### ISSUE THREAD

**Issue by andycampbell92** [rails-sqlserver/tiny_tds#406]
## Environment

**Operating System**
Docker ruby container: ```FROM ruby:2.5.1```
```
# lsb_release -a; uname -a
  No LSB modules are available.
  Distributor ID:	Debian
  Description:	Debian GNU/Linux 9.4 (stretch)
  Release:	9.4
  Codename:	stretch
  Linux 38355ddb5953 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 GNU/Linux
```

```
# tsql -C 
  Version: freetds v1.00.27
  freetds.conf directory: /usr/local/etc
  MS db-lib source compatibility: no
  Sybase binary compatibility: no
  Thread safety: yes
  iconv library: yes
  TDS version: 7.3
  iODBC: no
  unixodbc: no
  SSPI "trusted" logins: no
  Kerberos: no
  OpenSSL: yes
  GnuTLS: no
  MARS: no
```

```
# tsql-ttds -C
  [TinyTds][v2.1.1][tsql]: /usr/local/bin/tsql
  Compile-time settings (established with the "configure" script)
  Version: freetds v1.00.27
  freetds.conf directory: /usr/local/etc
  MS db-lib source compatibility: no
  Sybase binary compatibility: no
  Thread safety: yes
  iconv library: yes
  TDS version: 7.3
  iODBC: no
  unixodbc: no
  SSPI "trusted" logins: no
  Kerberos: no
  OpenSSL: yes
  GnuTLS: no
  MARS: no
```

**Ruby details**
```
ruby 2.5.1
tiny_tds 2.1.1
sequel 5.6.0
```

**Connection code**
```
  DB = Sequel.connect(
    adapter: 'tinytds',
    username: Settings.db.user,
    password: Settings.db.password,
    host: Settings.db.host,
    database: Settings.db.name,
    azure: true
    port: Settings.db.port)
```

## Description
I am receiving the following error when my app trys to connect to an azure SQL database:

```app_1      | Sequel::DatabaseDisconnectError: TinyTds::Error: Write to the server failed
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:61:in `execute'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:61:in `block (2 levels) in execute'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/database/logging.rb:38:in `log_connection_yield'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:60:in `block in execute'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/database/connecting.rb:269:in `synchronize'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:34:in `execute'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:1085:in `execute'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/adapters/tinytds.rb:207:in `fetch_rows'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:937:in `with_sql_each'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:947:in `with_sql_first'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/placeholder_literalizer.rb:159:in `first'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/dataset/actions.rb:241:in `first'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/model/plugins.rb:33:in `first'
app_1      | 	/app/vendor/bundle/ruby/2.5.0/gems/sequel-5.6.0/lib/sequel/model/base.rb:409:in `find'
```

It seems like this bug occurs when I have not connected to the database in some time i.e when I refresh the page and the application trys to connect to the database again it will work.

The failure is instant on trying to connect so I do not believe it is timing out. Is there a parameter to retry connection on failure?

**Comment by metaskills** [comment]
Retry connections on failures are left to higher up libraries like Sequel or ActiveRecord's connection pool.

**Comment by andycampbell92** [comment]
```
# Set connection to be validated every 5 minutes (default 1 hour)
# Fixes 'database write error' on azure sql instance
DB.extension :connection_validator
DB.pool.connection_validation_timeout = 300
```

For anyone else struggling with this I did the above with the Sequel gem to validate the connection every 5 minutes (almost definately overkill) probably every hour would be sufficient. I haven't seen this error since and it has been several days.

**Comment by metaskills** [comment]
Thank you for following up!
