### ISSUE TITLE
Won't install on Ruby 2.5.1

### ISSUE THREAD

**Issue by vassilvk** [rails-sqlserver/tiny_tds#408]
## Environment

**Operating System**
* Microsoft Windows 10 Enterprise, 10.0.14393 Build 14393

**Ruby Environment**
* Ruby 2.5.1-1 (x64) with built-in Ruby Devkit

**TinyTDS Version and Information**
* tiny_tds 2.1.1

## Description

Trying to install tiny_tds on Ruby 2.5.1 yields an error:

```
$ gem install tiny_tds
```

```
ERROR:  Error installing tiny_tds:
        The last version of tiny_tds (>= 0) to support your Ruby & RubyGems was 2.1.1. Try installing it with `gem install tiny_tds -v 2.1.1`
        tiny_tds requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.
```

**Comment by larskanis** [comment]
The binary gem version needs to be updated. As a work-around until this is done, you can install the source gem like so:
```
$ gem inst tiny_tds --platform ruby
```

If you're using a `Gemfile`, insert something like this:
```
gem "tiny_tds", git: "https://github.com/rails-sqlserver/tiny_tds"
```

**Comment by stibra** [comment]
This does not work, error in log file: 

I, [2018-05-28T08:25:50.616524 #2324]  INFO -- : Started GET "/" for [fe80::d4f5:86c5:78e4:f169%3]:61355 at 2018-05-28 08:25:50 +0200
F, [2018-05-28T08:25:50.622495 #2324] FATAL -- : 
LoadError (cannot load such file -- tiny_tds):
  activesupport (4.2.10) lib/active_support/dependencies.rb:274:in `require'
  activesupport (4.2.10) lib/active_support/dependencies.rb:274:in `block in require'
  activesupport (4.2.10) lib/active_support/dependencies.rb:240:in `load_dependency'
  activesupport (4.2.10) lib/active_support/dependencies.rb:274:in `require'
  activerecord-sqlserver-adapter (4.2.18) lib/active_record/sqlserver_base.rb:9:in `sqlserver_connection'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:438:in `new_connection'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:448:in `checkout_new_connection'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
  c:/Ruby200/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
  c:/Ruby200/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:571:in `retrieve_connection'
  activerecord (4.2.10) lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  activerecord (4.2.10) lib/active_record/connection_handling.rb:87:in `connection'
  activerecord (4.2.10) lib/active_record/query_cache.rb:51:in `restore_query_cache_settings'
  activerecord (4.2.10) lib/active_record/query_cache.rb:43:in `rescue in call'
  activerecord (4.2.10) lib/active_record/query_cache.rb:30:in `call'
  activerecord (4.2.10) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.10) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.10) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.10) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.10) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.10) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.10) lib/rails/rack/logger.rb:22:in `call'
  request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.10) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.10) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.10) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.10) lib/rack/sendfile.rb:113:in `call'
  actionpack (4.2.10) lib/action_dispatch/middleware/ssl.rb:24:in `call'
  railties (4.2.10) lib/rails/engine.rb:518:in `call'
  railties (4.2.10) lib/rails/application.rb:165:in `call'
  rack (1.6.10) lib/rack/content_length.rb:15:in `call'
  puma (3.11.4) lib/puma/configuration.rb:225:in `call'
  puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
  puma (3.11.4) lib/puma/server.rb:446:in `process_client'
  puma (3.11.4) lib/puma/server.rb:306:in `block in run'
  puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by larskanis** [comment]
@stibra Make sure you uninstalled all `x64-mingw32` versions of the tiny_tds gem. I updated my comment above accordingly.

I tested this successfully with rails-5.2.0. Not sure whether rails-4.2.10 is fully compatible to ruby-2.5 as it is released on 2017-09-27.

How did you add tiny_tds to you Gemfile? Can you please post a log of `bundle install`?

**Comment by metaskills** [comment]
> The binary gem version needs to be updated

What would be the checklist for that? Just a normal update or something more?
