### ISSUE TITLE
Include FreeTDS Binaries In Native Gem

### ISSUE THREAD

**Issue by metaskills** [rails-sqlserver/tiny_tds#72]
FreeTDS includes the following binaries. Here is a URL of their description.

http://www.freetds.org/userguide/usefreetds.htm

 ∴ tree ports/i686-darwin11.2.0/freetds/0.91/bin  
ports/i686-darwin11.2.0/freetds/0.91/bin
├── bsqldb
├── datacopy
├── defncopy
├── fisql
├── freebcp
├── osql
├── tdspool
└── tsql

We would like to hook into rake-compiler to include these in native gem. Once this is done, I propose using:

1) datacopy/freebcp - From the ActiveRecord Warehouse ETL project or any bulk copy tasks.
2) tsql - With a patch to the adapter to for the `db:console` rake task.

**Comment by ginolon** [comment]
In 2015 there is the same problem still... any news?

**Comment by larskanis** [comment]
If #207 is merged, we could bundle the freetds sources as tar file into the gem, so that it is compiled at gem install. This is often the most portable way. It is also how nokogiri ships the gems.

**Comment by ginolon** [comment]
@larskanis You're telling me that as soon as the # 207 will be merged I may install tinytds on Heroku without pain in the ass?

**Comment by larskanis** [comment]
@ginolon possibly... But it still depends on the devel packages of libiconv and openssl, which is surely more standard than freetds packages. I didn't use Heroku, so far, but if it helps, I could upload such a fat source gem for you.

**Comment by ginolon** [comment]
@larskanis man of the year. Please, thanks. I'm going crazy for how to proceed with my risicate skills on these topics.

**Comment by larskanis** [comment]
The gem files are uploaded [here](https://github.com/larskanis/tiny_tds/releases/tag/0.6.3.rc1.lars1) . I thought there is a way to let bundler download the gem from this url, but unfortunately it is not. So I'm not sure, how you get this gem uploaded to Heroku. If you can use a script for install, then wget and gem inst should be enough (like described beneath the download).

**Comment by ginolon** [comment]
Can I upload it on rubygems.org?

**Comment by larskanis** [comment]
No, you probably don't have the permissions to do this.

**Comment by ginolon** [comment]
@larskanis Ok. I'm testing it on Heroku. I go in my tmp directory and accomplish good these steps:

```
wget https://github.com/larskanis/tiny_tds/releases/download/0.6.3.rc1.lars1/tiny_tds-0.6.3.rc1.lars1-x64-mingw32.gem
gem install -l tiny_tds-0.6.3.rc1.lars1-x64-mingw32.gem
```

But now if i do `git push heroku master` with in my Gemfile this `gem "tiny_tds", "0.6.3.rc1.lars1"` Heroku says to me:

```
 Could not find gem 'tiny_tds (= 0.6.3.rc1.lars1) ruby' in any of the gem sources
remote:        listed in your Gemfile or installed on this machine.
```

**Comment by larskanis** [comment]
Don't install the Windows binary gem - remove 'x64-mingw32' !

**Comment by ginolon** [comment]
Oh! Right! Now I'm trying with this:

```
gem uninstall tiny_tds
Successfully uninstalled tiny_tds-0.6.3.rc1.lars1-x64-mingw32

rm tiny_tds-0.6.3.rc1.lars1-x64-mingw32.gem
wget https://github.com/larskanis/tiny_tds/releases/download/0.6.3.rc1.lars1/tiny_tds-0.6.3.rc1.lars1.gem
Saving to: ‘tiny_tds-0.6.3.rc1.lars1.gem’

100%[======================================>] 2,403,840   2.28MB/s   in 1.0s

2015-07-28 17:10:57 (2.28 MB/s) - ‘tiny_tds-0.6.3.rc1.lars1.gem’ saved [2403840/2403840]

gem install -l tiny_tds-0.6.3.rc1.lars1.gem
Building native extensions.  This could take a while...
ERROR:  Error installing tiny_tds-0.6.3.rc1.lars1.gem:
        ERROR: Failed to build gem native extension.

    /app/vendor/ruby-2.1.6/bin/ruby extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/app/vendor/ruby-2.1.6/bin/ruby
/app/vendor/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- mini_portile (LoadError)
        from /app/vendor/ruby-2.1.6/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from extconf.rb:6:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /app/vendor/ruby-2.1.6/lib/ruby/gems/2.1.0/gems/tiny_tds-0.6.3.rc1.lars1 for inspection.
Results logged to /app/vendor/ruby-2.1.6/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars1/gem_make.out
```

**Comment by ginolon** [comment]
@larskanis Now i'm installing `mini_portile`:

```
gem install mini_portile
Fetching: mini_portile-0.6.2.gem (100%)
Successfully installed mini_portile-0.6.2
Parsing documentation for mini_portile-0.6.2
Installing ri documentation for mini_portile-0.6.2
Done installing documentation for mini_portile after 0 seconds
1 gem installed
```

and now I'm retrying...

**Comment by ginolon** [comment]
I tried also to upload the gem to Gemfury in a private repository and tried to do `git push heroku master` from there with `source` in my Gemfile from the private repository. The push was ok, but if I restart the app here is the same error:

```
2015-07-28T17:44:08.210056+00:00 heroku[web.1]: Starting process with command `bin/rails server -p 22434 -e production`
2015-07-28T17:44:12.801287+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars1/tiny_tds/tiny_tds.so (LoadError)
```

**Comment by larskanis** [comment]
@ginolon There is a freetds version already installed, that seems to be usable, so that the tiny_tds-0.6.3.rc1.lars1.gem picks this one. Let me add an option to force install from source.

**Comment by ginolon** [comment]
@larskanis I feel that I'm close. It's a privilege for me to work with people like you. Thanks, really.

**Comment by larskanis** [comment]
@ginolon I've uploaded another version, that allows option `gem install -l tiny_tds-0.6.3.rc1.lars2.gem -- --disable-system-freetds` . Good luck!

**Comment by metaskills** [comment]
@larskanis Thanks for the help. I was going to ask in #207 after FreeTDS FTP was working if it was possible to build pre-compiled gems for different platforms. Is that what you did `tiny_tds-0.6.3.rc1.lars1.gem` in that link? What platform is that for and does it have static libs?

I can easily push #207 forward and grant gem push access... but I really want to test first.

**Comment by larskanis** [comment]
@metaskills No, `tiny_tds-0.6.3.rc1.lars2.gem` bundles the source freetds tar file into the gem - not the binary.  So this is somewhat off-topic here. It is great for offline installations or when ftp.freetds.org is down. My experience is, that binary builds on Linux are too dependent on the particular distribution version.

**Comment by ginolon** [comment]
@larskanis I'm so so sorry. Nothing again. This is the error:

```
Starting process with command `bin/rails server -p 55294 -e production`
2015-07-29T09:08:12.673905+00:00 app[web.1]: /app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars2/tiny_tds/tiny_tds.so (LoadError)
```

If I check `gem list` in my `heroku run bash` I find this:

`tiny_tds (0.6.3.rc1.lars2)`

but then when I deploy (I tried also to reinstall tiny_tds (0.6.3.rc1.lars2) after and before the deploy) the error is the same: **damn libsybdb.so.5**.

**Comment by larskanis** [comment]
@ginolon A libsybdb.so.5 seems to be there, but is not used. Can you set the library path like this and run the following commands in the heroku console?
``` sh
export LD_LIBRARY_PATH=/app/vendor/ruby-2.1.6/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars2/ports/x86_64-unknown-linux-gnu/lib/

ls -l $LD_LIBRARY_PATH

ldd /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars2/tiny_tds/tiny_tds.so
```
If the libsybdb.so.5 is there you could start rails with LD_LIBRARY_PATH set accordingly.


Additionally can you uninstall and reinstall tiny_tds like this:
```
gem uninst tiny_tds
env MAKE="make V=1" gem install -l tiny_tds-0.6.3.rc1.lars2.gem -- --disable-system-freetds
cat /app/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static/tiny_tds-0.6.3.rc1.lars2/gem_make.out
```
The `gcc -shared -o tiny_tds.so` line is interesting in `gem_make.out`.

**Comment by ginolon** [comment]
Nothing. After install this is my folder:

```
~/vendor/bundle/ruby/2.1.0/extensions/x86_64-linux/2.1.0-static $ dir
dir
bcrypt-3.1.10  nokogiri-1.6.6.2  pg-0.18.2    puma-2.11.3
json-1.8.2     pg-0.18.1         puma-2.11.2
```

**Comment by larskanis** [comment]
@ginolon I just signed up to heroku and tried tiny_tds in a free account. I didn't setup a rails app and don't have public database server, to connect to. So I started per `heroku run:detached ...` . It looks like this:
```sh
2015-07-29T14:02:30.799906+00:00 heroku[run.3666]: Starting process with command `bash -c 'wget https://github.com/larskanis/tiny_tds/releases/download/0.6.3.rc1.lars2/tiny_tds-0.6.3.rc1.lars2.gem && gem inst mini_portile tiny_tds-0.6.3.rc1.lars2.gem' && ldd /app/vendor/ruby-2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/tiny_tds-0.6.3.rc1.lars2/tiny_tds/tiny_tds.so && ruby -rtiny_tds -e "TinyTds::Client.new host: %q[172.20.192.59] "`
2015-07-29T14:02:31.356074+00:00 heroku[run.3666]: State changed from starting to up
2015-07-29T14:02:33.691318+00:00 app[run.3666]: Resolving github.com (github.com)... 192.30.252.131
[...]
2015-07-29T14:02:33.829940+00:00 app[run.3666]:   2300K .......... .......... .......... .......... .......... 99% 74.7M 0s
2015-07-29T14:02:33.830071+00:00 app[run.3666]:   2350K .                                                     100% 2861G=0.05s
2015-07-29T14:02:33.830073+00:00 app[run.3666]: 
2015-07-29T14:02:33.830224+00:00 app[run.3666]: 2015-07-29 14:02:33 (48.7 MB/s) - ‘tiny_tds-0.6.3.rc1.lars2.gem’ saved [2407936/2407936]
2015-07-29T14:02:33.830226+00:00 app[run.3666]: 
2015-07-29T14:03:04.749579+00:00 app[run.3666]: Successfully installed mini_portile-0.6.2
2015-07-29T14:03:04.749585+00:00 app[run.3666]: Parsing documentation for mini_portile-0.6.2
2015-07-29T14:03:04.749587+00:00 app[run.3666]: Installing ri documentation for mini_portile-0.6.2
2015-07-29T14:03:04.749588+00:00 app[run.3666]: Done installing documentation for mini_portile after 0 seconds
2015-07-29T14:03:04.749590+00:00 app[run.3666]: Building native extensions.  This could take a while...
2015-07-29T14:04:51.426184+00:00 app[run.3666]: unable to convert "\xA0" from ASCII-8BIT to UTF-8 for ext/tiny_tds/tmp/x86_64-unknown-linux-gnu/ports/freetds/0.91/freetds-0.91.112/src/tds/bulk.c, skipping
2015-07-29T14:05:18.319648+00:00 app[run.3666]: Successfully installed tiny_tds-0.6.3.rc1.lars2
2015-07-29T14:05:18.319653+00:00 app[run.3666]: Parsing documentation for tiny_tds-0.6.3.rc1.lars2
2015-07-29T14:05:18.319654+00:00 app[run.3666]: Installing ri documentation for tiny_tds-0.6.3.rc1.lars2
2015-07-29T14:05:18.319656+00:00 app[run.3666]: Done installing documentation for tiny_tds after 37 seconds
2015-07-29T14:05:18.319658+00:00 app[run.3666]: 2 gems installed
2015-07-29T14:05:18.380808+00:00 app[run.3666]:         linux-vdso.so.1 =>  (0x00007ffed8705000)
2015-07-29T14:05:18.380816+00:00 app[run.3666]:         libsybdb.so.5 => /app/vendor/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/tiny_tds-0.6.3.rc1.lars2/ports/x86_64-unknown-linux-gnu/lib/libsybdb.so.5 (0x00007f1a4e82d000)
2015-07-29T14:05:18.380818+00:00 app[run.3666]:         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1a4e468000)
2015-07-29T14:05:18.380822+00:00 app[run.3666]:         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f1a4e24a000)
2015-07-29T14:05:18.380824+00:00 app[run.3666]:         /lib64/ld-linux-x86-64.so.2 (0x00007f1a4ec99000)
2015-07-29T14:06:18.528494+00:00 app[run.3666]: /app/vendor/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/tiny_tds-0.6.3.rc1.lars2/lib/tiny_tds/client.rb:74:in `connect': Unable to connect: Adaptive Server is unavailable or does not exist (TinyTds::Error)
2015-07-29T14:06:18.528501+00:00 app[run.3666]:         from /app/vendor/ruby-2.2.0/lib/ruby/gems/2.2.0/gems/tiny_tds-0.6.3.rc1.lars2/lib/tiny_tds/client.rb:74:in `initialize'
2015-07-29T14:06:18.528503+00:00 app[run.3666]:         from -e:1:in `new'
2015-07-29T14:06:18.528504+00:00 app[run.3666]:         from -e:1:in `<main>'
2015-07-29T14:06:19.332313+00:00 heroku[run.3666]: State changed from up to complete
2015-07-29T14:06:19.319510+00:00 heroku[run.3666]: Process exited with status 1
```
So `gem install` builds with freetds, installs and uses `libsybdb.so.5` successfully and runs in a ruby session. The connection attempt finally fails, but at this point in time all libraries are already loaded.

I'm not sure, what the difference is in your setup (because I'm completely new to heroku). Maybe some interference with some buildpack?

**Comment by larskanis** [comment]
@ginolon I added the tiny_tds gem to the Gemfile and it gives me the same error that you got:
```
2015-07-29T15:26:35.824268+00:00 app[web.1]: /app/vendor/bundle/ruby/2.2.0/gems/tiny_tds-0.6.3.rc1.lars2/lib/tiny_tds.rb:28:in `require': libsybdb.so.5: cannot open shared object file: No such file or directory - /app/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/tiny_tds-0.6.3.rc1.lars2/tiny_tds/tiny_tds.so (LoadError)
```
So I did a search:
```
heroku run:detached "bash -c 'find /app -name libsybdb.so.5'"
```
and added the path as a environment variable:
```
heroku config:add LD_LIBRARY_PATH=/app/vendor/bundle/ruby/2.2.0/gems/tiny_tds-0.6.3.rc1.lars2/ports/x86_64-unknown-linux-gnu/lib/
```
That seems to work: https://tranquil-caverns-6259.herokuapp.com/

The problem is, that heroku seems to move the gem build dir to another path after installation. Therefore the build time library paths are not valid at run time, anymore. I don't have a good idea, right now, other than doing a static build or using the above workaround.

**Comment by ginolon** [comment]
@larskanis Thanks many times. I can confirm it works with `LD_LIBRARY_PATH` variable. I wonder whether it is the best way to do this. Now it works. We will see.

**Comment by larskanis** [comment]
@ginolon I added [another prerelease version](https://github.com/larskanis/tiny_tds/releases/tag/0.6.3.rc1.lars3) of the tiny_tds gem, that works with changed paths between build and run time. This is special for heroku, and usually doesn't happen at a typical desktop or server use. Nevertheless it should now work without setting LD_LIBRARY_PATH.

**Comment by ginolon** [comment]
This release has wrong date, hasn't? 29 May the lars3?

**Comment by larskanis** [comment]
@ginolon What's wrong with it? Maybe another timezone? Does the lars3-gem work for you?

**Comment by metaskills** [comment]
I just noticed that the FreeTDS FTP is working again. Gonna start up again on #207 and get that merged in. @larskanis I'd like to talk about getting you repo/gem access. Mind stopping by our Gitter and chatting?

**Comment by larskanis** [comment]
@metaskills Thank you very much for your offer! But I don't like MSSQL. Most of my daily work is on Postgres (and therefore I maintain the pg.gem). The next time I'm angry about MSSQL, I possibly install a bomb into tiny_tds... No, better leave me out of the repo/gem and check the pull requests carefully :wink: 

Joking aside: It's OK for me to contribute per pull request, or to upload gems to github/gemfury to debug a particular issue (like this above). I respect you as the maintainer of this project, and I don't wan't to mess with your business. As long as the project is actively maintained, everything is fine!

If I can help with #207 - just ask!

**Comment by metaskills** [comment]
Closing this issue our for a clean version #227

**Comment by metaskills** [comment]
This work was done in #251 which duplicates #227 and is now in master. We are only going to use `tsql` for starters.

**Comment by metaskills** [comment]
## GO HERE

https://github.com/rails-sqlserver/heroku-buildpack-freetds
